# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ClusterLabs
email: andrew@beekhof.net
description: Community hub for open-source high-availability software

url: http://www.clusterlabs.org/
google_analytics: UA-8156370-1

# Build settings
theme: minima
destination: ../html
gems:
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

# All content generated outside of jekyll, or not yet converted to jekyll,
# must be listed here, or jekyll will erase it when building the site.
# Though not documented as such, the values here function as prefix matches.
keep_files:
  - 404.html
  - abi
  - banner.html
  - beekhof.net
  - components.html
  - coverity
  - developers.html
  - doc
  - doxygen
  - faq.html
  - footer.html
  - global
  - help.html
  - humans.txt
  - images
  - man
  - pacemaker.html
  - pacemaker.png
  - Pictures
  - polls
  - quickstart-common.html
  - quickstart.html
  - quickstart-redhat-6.html
  - quickstart-redhat.html
  - quickstart-suse-11.html
  - quickstart-suse.html
  - quickstart-ubuntu.html
  - robots.txt
  - rpm-test
  - rpm-test-next
  - rpm-test-rhel
  - stylesheets
  - versions.html
