# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ClusterLabs
email: andrew@beekhof.net
description: Community hub for open-source high-availability software

url: http://www.clusterlabs.org/
google_analytics: UA-8156370-1

# Build settings
theme: minima
destination: ../html
gems:
  - jekyll-assets
  - font-awesome-sass
include:
  - abi
  - doc
  - doxygen
  - global
  - man
  - polls
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.theme

# All content generated outside of jekyll, or not yet converted to jekyll,
# must be listed here, or jekyll will erase it when building the site.
# Though not documented as such, the values here function as prefix matches.
keep_files:
  - abi
  - doc
  - doxygen
  - global
  - images
  - man
  - Pictures
  - rpm-test
  - rpm-test-next
  - rpm-test-rhel
